server:
  port: 8081

app-config:
  client:
    swapi:
      base-uri: https://swapi.dev/api
      people: ${app-config.client.swapi.base-uri}/people
      planets: ${app-config.client.swapi.base-uri}/planets
      films: ${app-config.client.swapi.base-uri}/films
      species: ${app-config.client.swapi.base-uri}/species
      vehicles: ${app-config.client.swapi.base-uri}/vehicles
      starships: ${app-config.client.swapi.base-uri}/starships